pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    
    stages {
        stage('checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/yap-john/playground.git']])
            }
        }
        stage('Terraform init') {
            steps {
                dir('eks-terraform/') {
                    sh 'terraform init'
                    sh 'terraform plan'
                    sh 'terraform apply --auto-approve'
                    sh 'terraform output > terraform_outputs'
                }
            }
        }
        stage('build') {
            steps {
                sh 'chmod +x eks-terraform.sh'
                sh 'eks-terraform.sh'
            }
        }
        
    }
}
