---
apiVersion: v1
kind: Service
metadata:
  name: alb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  selector:
    name: webapp-pod
    type: front-end #edit to the label of deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
